spring:
  output:
      ansi:
        enabled: always
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sb_mybatis?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: imhope
    password: 0987
logging:
  level:
    com.ll.exam.sb_mybatis: debug